yolo_model:

  config_file:
    name: deeplearning.cfg
  weight_file:
    name: deeplearning_final.weights
  threshold:
    value: 0.7
  detection_classes:
    names:
      - Green
      - Left
      - Red
      - StraightLeft
      - A1
      - A2
      - A3
      - B1
      - B2
      - B3
