yolo_model:

  config_file:
    name: delivery_traffic.cfg
  weight_file:
    name: delivery_traffic_final.weights
  threshold:
    value: 0.6
  detection_classes:
    names:
      - A1
      - A2
      - A3
      - B1
      - B2
      - B3
      - Green
      - Left
      - Red
      - StraightLeft
