yolo_model:

  config_file:
    name: yolov3_delivery.cfg
  weight_file:
    name: yolov3_delivery_final.weights
  threshold:
    value: 0.5
  detection_classes:
    names:
      - A1
      - A2
      - A3
      - B1
      - B2
      - B3
