yolo_model:

  config_file:
    name: yolov3_traffic_sign.cfg
  weight_file: 
    name: traffic_sign_final.weights
  threshold:
    value: 0.5
  detection_classes:
    names:
      - Green
      - Left
      - Red
      - StraightLeft
